### ISSUE TITLE
Replace govukcli with other tooling

### ISSUE THREAD

**Issue by benthorner** [alphagov/govuk-aws#1159]
[govukcli](https://github.com/alphagov/govuk-aws/blob/master/tools/govukcli) was [introduced in 2017](https://github.com/alphagov/govuk-aws/commit/a3e413fdb4a7ea4caaf621988584ea698e0053d2) to help people run 'assume-role' and 'ssh' commands against AWS machines on GOV.UK. Since that time, we've seen a divergence in the approaches people use in practice and in our docs, which is duplicated effort and confusing for new starters. The naming 'govukcli' also belies the fact that it is not an agreed or actual CLI for running all GOV.UK tools. 

We would like to replace govukcli with other tooling, and this issue is a precursor to an RFC for the SSH sub-command specifically.

# govukcli aws

> Usage: govukcli aws [options]
>
> Gets a temporary session for the requested context, including asking for
your MFA token if needed. By default, passes arguments to the "aws" CLI tool. Use the "invoke" command to set up the credentials then invoke another tool. Requires your AWS credentials to be set up as in the GOV.UK Developer Docs:
>
>https://docs.publishing.service.gov.uk/manual/user-management-in-aws.html#storing-credentials-on-disk

We believe this can be replaced with [gds-cli](https://github.com/alphagov/gds-cli), which means we benefit for using standard GDS tooling to meet a non-GOV.UK-specific need. Our approach to making this change will be:

- [x] Change `govukcli aws` to output migration instructions to use gds-cli
- [x] Update and consolidate the GOV.UK Developer docs for AWS (tooling)
   - [x] https://docs.publishing.service.gov.uk/manual/govuk-in-aws.html
   - [x] https://docs.publishing.service.gov.uk/manual/aws-cli-access.html
   - [x] https://docs.publishing.service.gov.uk/manual/aws-console-access.html
   - [x] https://docs.publishing.service.gov.uk/manual/concept-of-stacks.html
   - [x] https://docs.publishing.service.gov.uk/manual/set-up-aws-account.html
   - [x] https://docs.publishing.service.gov.uk/manual/deploying-terraform.html

@issyl0 will be leading on this.

# govukcli ssh

> Usage: govukcli ssh [options]
>
> By default it will expect a Puppet node class (eg backend, frontend), and will attempt to SSH to a random instance within that class. If only a single instance exists, then it will SSH to that instance (eg puppetmaster, jenkins).
>
> Options:
>
> set-user <username>  Set a different username to SSH with than the default shell user ($(whoami)).
>
> node-types List the types of instances available to connect to.
>
> node-list <machine>  List the machines for a particular node. Try node-list whitehall_backend.

## Phase 1

We believe this can be replaced with [govuk-connect](https://github.com/alphagov/govuk-guix/blob/master/bin/govuk-connect). Our approach to making this change will be to create a prototype repo that will help people understand the subsequent RFC:

- [x] Extract [govuk-connect](https://github.com/alphagov/govuk-guix/blob/master/bin/govuk-connect) into a new, dedicated, prototype repo
- [x] Ensure the prototype repo has setup and usage instructions

@cbaines will be leading on this.

## Phase 2

We know there are a variety of preferences for SSH tooling among GOV.UK developers and we're conscious we need to consult people before making further changes:

 - [x] Update and consolidate the GOV.UK Developer docs for setting up SSH
   - [x] https://docs.publishing.service.gov.uk/manual/ssh-config.html
   - [x] https://docs.publishing.service.gov.uk/manual/get-ssh-access.html
   - [x] https://docs.publishing.service.gov.uk/manual/howto-ssh-to-machines-in-aws.html
   - [x] https://docs.publishing.service.gov.uk/manual/ssh-from-vm.html
   - [x] https://docs.publishing.service.gov.uk/manual/get-started.html
 - [x] Signpost installing the govuk-connect tool as part of the initial SSH setup
 - [x] Add further documentation about how to do SSH without govuk-connect
 - [x] Update all other GOV.UK Developer docs to refer to govuk-connect only
 - [x] Update gds-cli to work with the new govuk-connect repo (for those using it)

**Comment by benthorner** [comment]
@cbaines @issyl0 could you take a look and let me know if something needs changing?

**Comment by issyl0** [comment]
Looks good to me. Thanks for writing it up.

I’ve edited for completeness to say who will be leading on which bits.

**Comment by cbaines** [comment]
I've done the very initial work to setup a `govuk-connect` Git repository for `govuk-connect`: https://github.com/alphagov/govuk-connect/pull/1

There's probably a few things to fix and tweak, but it should somewhat work.

**Comment by issyl0** [comment]
It works! There's now a RubyGem for `govuk-connect` (thanks to @theseanything!) and the next release of `gds-cli` will search for `govuk-connect` as the command. :heart: Now "all" we have to do is the rest of the things on this checklist!

There's been a fair bit of confusion around having to use separate tools for AWS and SSH, so the `gds govuk c` subcommand can only be a good thing IMO.

**Comment by issyl0** [comment]
I think we can call this done! Thanks to everyone who helped out!
